In [ ]:
import numpy as np
a1 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
print("Array is:", a1)
print("Zero grid:", np.zeros((2, 4)))
print("One grid:", np.ones((2, 3)))
print("Even numbers:", np.arange(0, 12).reshape(3, 4))
# Indexing
print("Element at row 2, column 3:", a1[1, 2])
print("First row:", a1[0, :])
print("Second row:", a1[1, :])
# Slicing
print("First two rows:", a1[:2, :])
print("Last two columns:", a1[:, -2:])
print("First column:", a1[:, 0])
# Reshaping
a2 = np.arange(1, 13).reshape(3, 4)
print("Reshaped Array (3x4):", a2)
# Broadcasting
a3 = np.array([10, 20, 30])
print("Addition of array 1 and 3:", a1 + a3)
print("Floor division:", a3 // 5)
# Mathematical operations
print("Addition:", a1+2)
print("Subtraction:", a1 - 3)
print("Multiplication:", a1 * 3)
print("Division:", a1 / 2)
print("Square:", a1 ** 2)

Array is: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Zero grid: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
One grid: [[1. 1. 1.]
 [1. 1. 1.]]
Even numbers: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Element at row 2, column 3: 6
First row: [1 2 3]
Second row: [4 5 6]
First two rows: [[1 2 3]
 [4 5 6]]
Last two columns: [[2 3]
 [5 6]
 [8 9]]
First column: [1 4 7]
Reshaped Array (3x4): [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Addition of array 1 and 3: [[11 22 33]
 [14 25 36]
 [17 28 39]]
Floor division: [2 4 6]
Addition: [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Subtraction: [[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]
Multiplication: [[ 3  6  9]
 [12 15 18]
 [21 24 27]]
Division: [[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
Square: [[ 1  4  9]
 [16 25 36]
 [49 64 81]]
